package domain.word;

import java.util.List;
import java.util.Random;

public class WordRepository {
    private final List<String> WORDS = List.of(
            "airplane",
            "apple",
            "arm",
            "bakery",
            "banana",
            "bank",
            "bean",
            "belt",
            "bicycle",
            "biography",
            "blackboard",
            "boat",
            "bowl",
            "broccoli",
            "bus",
            "car",
            "carrot",
            "chair",
            "cherry",
            "cinema",
            "class",
            "classroom",
            "cloud",
            "coat",
            "cucumber",
            "desk",
            "dictionary",
            "dress",
            "ear",
            "eye",
            "fog",
            "foot",
            "fork",
            "fruits",
            "hail",
            "hand",
            "head",
            "helicopter",
            "hospital",
            "ice",
            "jacket",
            "kettle",
            "knife",
            "leg",
            "lettuce",
            "library",
            "magazine",
            "mango",
            "melon",
            "motorcycle",
            "mouth",
            "newspaper",
            "nose",
            "notebook",
            "novel",
            "onion",
            "orange",
            "peach",
            "pharmacy",
            "pineapple",
            "plate",
            "pot",
            "potato",
            "rain",
            "shirt",
            "shoe",
            "shop",
            "sink",
            "skateboard",
            "ski",
            "skirt",
            "sky",
            "snow",
            "sock",
            "spinach",
            "spoon",
            "stationary",
            "stomach",
            "strawberry",
            "student",
            "sun",
            "supermarket",
            "sweater",
            "teacher",
            "thunderstorm",
            "tomato",
            "trousers",
            "truck",
            "vegetables",
            "vehicles",
            "watermelon",
            "wind");

    public String random() {
        Random random = new Random();
        return WORDS.get(random.nextInt(WORDS.size()));
    }
}
